# Basic Information 
title: Hanzhang Wang ç‹å«ç« 
position: è®²å¸ˆï¼Œç¡•å¯¼
affiliation: School of Computer Engineering and Science<br/>Shanghai University (ä¸Šæµ·å¤§å­¦)
email: ğŸ‘‹ hanzhangwang@shu.edu.cn

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Hanzhang Wang
description: Hanzhang Wang homepage
canonical: https://hanzhang-wang.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/hanzhang-wang
#linkedin: https://www.linkedin.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/profile.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
